adminIncident/urls.py
from django.urls import re_path, path

from adminIncident.views import AdminIncidentView, DeleteUserView, ChangeUserView

urlpatterns = [
    re_path(r'^$', AdminIncidentView.as_view(), name="adminincident"),
    re_path(r'^delete/(?P<id_user>\d+)$', DeleteUserView.as_view(), name="deleteuser"),
    re_path(r'^change/$', ChangeUserView.as_view(), name="change_user"),


    # re_path(r'^change/(?P<user_id>\d+)/$', ChangeUserView.as_view(), name="change_user"),



    # re_path(r'^headorion$', login_required(headorion_view.HeadOrionView.as_view()), name="headorion"),
    # re_path(r'^event$', login_required(event_view.EventView.as_view()), name="event"),
    # re_path(r'^operationalenv$', login_required(operationalenv_view.OperationalEnvView.as_view()), name="operationalenv"),
    # re_path(r'^face$', login_required(face_view.FaceView.as_view()), name="face"),
    # re_path(r'^journal$', login_required(journal_view.JournalView.as_view()), name="journal"),
    # re_path(r'^anlytics$', login_required(analytics_view.AnalyticsView.as_view()), name="analytics"),
    # re_path(r'^about$', login_required(about_view.AboutView.as_view()), name="about"),


]

incidentProject/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, re_path, include

from authOrion.views import StartView, RegisterFormView, LoginFormView, LogoutView, PasswordChangeView
from adminIncident.views import AdminIncidentView

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^adminincident/', include('adminIncident.urls')),
    re_path(r'^orion/', include('orion.urls')),
    re_path(r'^$', login_required(StartView.as_view()), name="start"),

    #Auth
    re_path(r'^register/', RegisterFormView.as_view(), name="register"),
    re_path(r'^login/', LoginFormView.as_view(), name="login"),
    re_path(r'^logout/', LogoutView.as_view(), name="logout"),
    re_path(r'^passwordchange/', PasswordChangeView.as_view(), name="passwordChange"),
]

orion/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import re_path, path, include

from orion.views import headorion_view, event_view, operationalenv_view, face_view, journal_view, analytics_view, about_view, titul_view, org_view, ajax_view

urlpatterns = [

    re_path(r'^headorion$', login_required(headorion_view.HeadOrionView.as_view()), name="headorion"),
    re_path(r'^event/', include([
        re_path(r'^$', event_view.EventView.as_view(), name="event"),
        re_path(r'^change$', event_view.ChangeEventView.as_view(), name="change_event"),
        re_path(r'^delete$', event_view.DeleteEventView.as_view(), name="delete_event"),
    ])),
    re_path(r'^face/', include([
        re_path(r'^$', face_view.FaceView.as_view(), name="face"),
        re_path(r'^add$', face_view.AddFaceView.as_view(), name="add_face"),
        re_path(r'^change$', face_view.ChangeFaceView.as_view(), name="change_face"),
        re_path(r'^delete$', face_view.DeleteFaceView.as_view(), name="delete_face"),
    ])),
    re_path(r'^titul/', include([
        re_path(r'^$', titul_view.TitulView.as_view(), name="titul"),
        re_path(r'^add$', titul_view.AddTitulView.as_view(), name="add_titul"),
        re_path(r'^change$', titul_view.ChangeTitulView.as_view(), name="change_titul"),
        re_path(r'^delete$', titul_view.DeleteTitulView.as_view(), name="delete_titul"),
    ])),
    re_path(r'^org/', include([
        re_path(r'^$', org_view.OrgView.as_view(), name="org"),
        re_path(r'^add$', org_view.AddOrgView.as_view(), name="add_org"),
        re_path(r'^change$', org_view.ChangeOrgView.as_view(), name="change_org"),
        re_path(r'^delete$', org_view.DeleteOrgView.as_view(), name="delete_org"),
    ])),
    re_path(r'^operationalenv/', include([
        re_path(r'^$', operationalenv_view.OperationalEnvView.as_view(), name="operationalenv"),
        re_path(r'^add$', operationalenv_view.AddOperationalEnvView.as_view(), name="add_operationalenv"),
        re_path(r'^change$', operationalenv_view.ChangeOperationalEnvView.as_view(), name="change_operationalenv"),
        re_path(r'^delete$', operationalenv_view.DeleteOperationalEnvView.as_view(), name="delete_operationalenv"),
    ])),
    re_path(r'^journal$', login_required(journal_view.JournalView.as_view()), name="journal"),
    re_path(r'^anlytics$', login_required(analytics_view.AnalyticsView.as_view()), name="analytics"),
    re_path(r'^about$', login_required(about_view.AboutView.as_view()), name="about"),

    # AJAX
    re_path(r'^count_event/', login_required(ajax_view.CountEventView.as_view()), name="count_event"),
    re_path(r'^show_event/', login_required(ajax_view.ShowEventView.as_view()), name="show_event"),

]

adminIncident/models.py
from django.db import models

# Create your models here.

orion/forms.py
from django import forms
from django.forms import ModelForm

from orion.models import Event, TypeMessage, Titul, Org, KlassifPriznakUK, KlassifPriznakUgroza, Face, TypeProverki, ResultProverki, OperativnayaObstanovka, Status, AdresAte, Zvanie, Subdivision


class EventForm(ModelForm):
    status = forms.ModelChoiceField(label="Статус", required=True, empty_label=None, queryset=Status.objects.all(), widget=forms.Select(attrs={"class": "custom-select mr-sm-2"}))
    date_vklyuch_doklad = forms.DateField(label="Дата включения в доклад", required=False, widget=forms.DateInput(format='%Y-%m-%d', attrs={"class": "form-control form-control-sm", "type": "date"}))
    type_message = forms.ModelChoiceField(label="Тип сообщения", queryset=TypeMessage.objects.all(), empty_label=None, required=True, widget=forms.Select(attrs={"class": "custom-select mr-sm-2"}))
    titul = forms.ModelChoiceField(label="Документ", queryset=Titul.objects.all(), required=False, widget=forms.Select(attrs={"class": "custom-select mr-sm-2"}))
    org = forms.ModelMultipleChoiceField(label="Организация", queryset=Org.objects.all(), required=False,
                                         widget=forms.SelectMultiple(attrs={"class": "form-control", "multiple": "multiple",
                                                                    "title": "Ничего не выбрано"}))
    date_registratsii = forms.DateField(label="Дата регистрации", required=True, widget=forms.DateInput(format='%Y-%m-%d', attrs={"class": "form-control form-control-sm", "type": "date"}))
    subdivision = forms.ModelChoiceField(label="Подразделение", required=False, empty_label=None, queryset=Subdivision.objects.all(), widget=forms.Select(attrs={"class": "custom-select mr-sm-2"}))
    region = forms.ModelChoiceField(label="Регион", required=True,  queryset=AdresAte.objects.all(), widget=forms.Select(attrs={"class": "custom-select mr-sm-2"}))
    # reg_number = forms.CharField(label="Регистрационный номер",  widget=forms.TextInput(attrs={"class": "form-control form-control-sm"}))
    sut_info = forms.CharField(label="Суть информации", required=True, widget=forms.Textarea(attrs={"class": "form-control form-control-sm", "cols": 2, "rows": 2}))
    klassif_priznak_UK = forms.ModelChoiceField(label="Классифицирующий признак (по статье УК РФ)", queryset=KlassifPriznakUK.objects.all(), required=False,
                                                widget=forms.Select(attrs={"class": "form-control form-control-sm selectpicker show-tick font-size-option", "data-live-search": "true", "data-size": "7"}))
    klassif_priznak_ugroza = forms.ModelChoiceField(label="Классифицирующий признак (угроза)", queryset=KlassifPriznakUgroza.objects.all(), required=False,
                                                    widget=forms.Select(attrs={"class": "form-control form-control-sm selectpicker show-tick font-size-option", "data-live-search": "true", "data-size": "7"}))
    klassif_priznak_text = forms.CharField(label="Классифицирующий признак (текст)", required=False, widget=forms.TextInput(attrs={"class": "form-control form-control-sm "}))
    rezolyutsiya_rukovodstva = forms.CharField(label="Резолюция руководства ВНГ, ГУСБ", required=False, widget=forms.Textarea(attrs={"class": "form-control form-control-sm", "cols": 2, "rows": 2}))
    date_start = forms.DateField(label="Дата начала", required=True, widget=forms.DateInput(format='%Y-%m-%d', attrs={"class": "form-control form-control-sm", "type": "date"}))
    date_finish = forms.DateField(label="Дата окончания", required=True, widget=forms.DateInput(format='%Y-%m-%d', attrs={"class": "form-control form-control-sm", "type": "date"}))
    ispolnitel_organ = forms.CharField(label="Исполнитель (Орган)", max_length=100, required=False, widget=forms.TextInput(attrs={"class": "form-control form-control-sm"}))
    ispolnitel_sotrudnik = forms.CharField(label="Исполннитель (Сотрудник)", max_length=100, required=False, widget=forms.TextInput(attrs={"class": "form-control form-control-sm"}))
    info_otrabotki_materiala = forms.CharField(label="Информация, полученная в ходе отработки материала", required=False, widget=forms.Textarea(attrs={"class": "form-control form-control-sm", "cols": 2, "rows": 2}))
    identified_face = forms.ModelMultipleChoiceField(label="В ходе проверки выявлены (установленны лица)", queryset=Face.objects.all(), required=False,
                                                     widget=forms.SelectMultiple(attrs={"class": "form-control", "multiple": "multiple"}))
    type_proverki = forms.ModelChoiceField(label="Вид проверки", queryset=TypeProverki.objects.all(), required=False, widget=forms.Select(attrs={"class": "custom-select mr-sm-2"}))
    rezult_proverki = forms.ModelChoiceField(label="Результат проверки", queryset=ResultProverki.objects.all(), required=False, widget=forms.Select(attrs={"class": "custom-select mr-sm-2"}))
    prinyatie_meri = forms.CharField(label="Принятые меры", required=False, widget=forms.Textarea(attrs={"class": "form-control form-control-sm", "cols": 2, "rows": 2}))
    otvet_zayavitelyu = forms.CharField(label="Ответ заявителю", required=False, widget=forms.Textarea(attrs={"class": "form-control form-control-sm", "cols": 2, "rows": 2}))
    ispolnenie_rezolyucii = forms.CharField(label="Исполнение резолюции руководства ВНГ, ГУСБ", required=False, widget=forms.Textarea(attrs={"class": "form-control form-control-sm", "cols": 2, "rows": 2}))
    date_otveta = forms.DateField(label="Дата ответа заявителю", required=False, widget=forms.DateInput(attrs={"class": "form-control form-control-sm", "type": "date"}))
    ishodyaschii_nomer = forms.CharField(label="Исходящий номер документа", max_length=50, required=False, widget=forms.TextInput(attrs={"class": "form-control form-control-sm"}))
    operativnaya_obstanovka = forms.ModelChoiceField(label="Оперативная обстановка", queryset=OperativnayaObstanovka.objects.all(), required=False,
                                                     widget=forms.Select(attrs={"class": "form-control form-control-sm selectpicker show-tick font-size-option", "data-live-search": "true", "data-size": "7"}))


    class Meta:
        model = Event
        exclude = [' date_creation', 'user',  'date_change', 'reg_number']



class TitulForm(ModelForm):
    name = forms.CharField(label="Наименование документа", required=True, max_length=300, widget=forms.TextInput(attrs={"class": "form-control form-control-sm"}))
    nomer_vhodyaschego = forms.CharField(label="Номер входящего документа", required=False, max_length=300, widget=forms.TextInput(attrs={"class": "form-control form-control-sm"}))
    date_vhodyaschego = forms.DateField(label="Дата входящего документа", required=False, widget=forms.DateInput(format='%Y-%m-%d', attrs={"class": "form-control form-control-sm", "type": "date"}))
    otkuda = forms.CharField(label="Откуда поступил документ", max_length=100, required=False, widget=forms.TextInput(attrs={"class": "form-control form-control-sm"}))
    ishodyaschii_nomer = forms.CharField(label="Исходящий номер документа", max_length=50, required=False, widget=forms.TextInput(attrs={"class": "form-control form-control-sm"}))
    date_ishodyaschego = forms.DateField(label="Дата исходящего документа", required=False, widget=forms.DateInput(format='%Y-%m-%d', attrs={"class": "form-control form-control-sm", "type": "date"}))

    class Meta:
        model = Titul
        exclude = ['date_vneseniya']


class OrgForm(ModelForm):
    name = forms.CharField(label="Наименование организации", required=True, max_length=300, widget=forms.TextInput(attrs={"class": "form-control form-control-sm"}))
    inn_ogrn = forms.CharField(label="ИНН (ОГРН)", required=False, max_length=300, widget=forms.TextInput(attrs={"class": "form-control form-control-sm"}))
    adres_organiz_ate = forms.ModelChoiceField(label="Адрес организации (АТЕ)", queryset=AdresAte.objects.all(), widget=forms.Select(attrs={"class": "custom-select mr-sm-2"}))
    adres_organiz = forms.CharField(label="Адрес организации", max_length=100, required=False, widget=forms.TextInput(attrs={"class": "form-control form-control-sm"}))
    inaya_informaciya = forms.CharField(label="Иная информация", required=False, widget=forms.Textarea(attrs={"class": "form-control form-control-sm", "cols": 2, "rows": 2}))

    class Meta:
        model = Org
        fields = '__all__'


class OperationalEnvForm(ModelForm):
    date = forms.DateField(label="Дата", required=True, widget=forms.DateInput(format='%Y-%m-%d', attrs={"class": "form-control form-control-sm", "type": "date"}))
    klassif_priznak_ugroza = forms.ModelChoiceField(label="Классифицирующий признак (угроза)", queryset=KlassifPriznakUgroza.objects.all(), required=False,
                                                    widget=forms.Select(attrs={"class": "form-control form-control-sm selectpicker show-tick font-size-option", "data-live-search": "true", "data-size": "7"}))
    klassif_priznak_text = forms.CharField(label="Классифицирующий признак (текст)", required=False, widget=forms.TextInput(attrs={"class": "form-control form-control-sm "}))
    sut_info = forms.CharField(label="Суть информации", required=True, widget=forms.Textarea(attrs={"class": "form-control form-control-sm", "cols": 2, "rows": 2}))
    prinyatie_meri = forms.CharField(label="Принятые меры", required=False, widget=forms.Textarea(attrs={"class": "form-control form-control-sm", "cols": 2, "rows": 2}))

    class Meta:
        model = OperativnayaObstanovka
        fields = '__all__'


class FaceForm(ModelForm):
    familiya = forms.CharField(label="Фамилия", required=True, max_length=100, widget=forms.TextInput(attrs={"class": "form-control form-control-sm "}))
    imya = forms.CharField(label="Имя", required=True, max_length=100, widget=forms.TextInput(attrs={"class": "form-control form-control-sm "}))

adminIncident/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseNotFound
from django.shortcuts import render
from django.contrib.auth.models import User, Group
from django.views.generic import TemplateView

from incidentProject.mixins import GroupRequiredMixin
from orion.models import Subdivision


class AdminIncidentView(GroupRequiredMixin, TemplateView):
    group_required = ['Админ']

    def get(self, request, *args, **kwargs):
        all_users = User.objects.all().exclude(username='admin')
        context = {"all_users": all_users}
        return render(request, "adminincident.html", context)


class DeleteUserView(GroupRequiredMixin, TemplateView):
    group_required = ['Админ']

    def get(self, request, *args, **kwargs):
        try:
            User.objects.get(id=self.kwargs['id_user']).delete()
            messages.success(request, "Пользователь удален!!!")
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        except:
            messages.error(request, "Пользователь не удален!!!")
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class ChangeUserView(GroupRequiredMixin, TemplateView):
    group_required = ['Админ']
    template_name = "changeuser.html"

    def get(self, request, *args, **kwargs):
        user_id = request.GET.get("user_id")
        if not user_id.isdigit():
            return HttpResponseNotFound('<h1>Нет такой страницы</h1>')
        else:
            user = User.objects.get(id=user_id)
            groups = Group.objects.all()
            subdivisions = Subdivision.objects.all()
            context = {"user": user, "groups": groups, "subdivisions": subdivisions}
            return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        try:
            user_id = request.POST.get("user_id")
            user = User.objects.get(id=user_id)
            user.first_name = request.POST.get("first_name")
            user.last_name = request.POST.get("last_name")
            user.email = request.POST.get("email")
            user.groups.set(request.POST.getlist("group"))
            user.userprofile.subdivision_id = request.POST.get("subdivision")
            user.save()
            messages.success(request, "Пользователь изменен!!!")
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        except:
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

adminIncident/templates/adminincident.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="author" content="Koldomov Viktor">
	<link rel="shortcut icon" type="image/x-icon" href={% static "vendor/images/favicon.ico" %}>
	<title>Администрирование</title>
	<!-- Bootstrap core CSS -->
	<link rel="stylesheet" href={% static "vendor/bootstrap/css/bootstrap.min.css" %}>
	<!-- Font Awesome core CSS -->
	<link rel="stylesheet" href={% static "vendor/icons/css/all.min.css" %}>
	<!-- Custom styles for this template -->
	<link rel="stylesheet" href={% static "css/simple-sidebar.css" %}>
	<link rel="stylesheet" href={% static "css/my.css" %}>
</head>
<body>
{% if messages %}
	{% for message in messages %}
		<div id="message" data-tags="{{ message.tags }}" hidden>{{ message }}</div>
	{% endfor %}
{% endif %}
<div class="d-flex justify-content-center">
	<img alt="#" height="40" src={% static "vendor/images/logo.png" %}>&nbsp;&nbsp;&nbsp;
	<h5 class="p-2">Информационный банк данных "Орион"</h5>
</div>
<div class="container-fluid" id="top-menu">
	<div class="row d-flex align-items-center">
		<div class="col-4">
				<ul id="breadcrumbs" style="margin: 0; padding: 0; list-style: none;">
						<li><a href={% url "start" %}> <i class="fas fa-home fa-lg"></i></a></li>
					{% block breadcrumbs %}
						<li><a class="current" href={% url 'adminincident' %} >Пользователи</a></li>
					{% endblock breadcrumbs %}
				</ul>
		</div>
		<div class="col-4 d-flex justify-content-center">
			<h4 style="color: #13010461;"><i class="fal fa-tools"></i>&nbsp;Администрирование</h4>
		</div>
		<div class="col-4 d-flex justify-content-end" style="color: #506154">
			<div class="p-2 bd-highlight"><i class="fas fa-user fa-2x"></i></div>
			<div class="p-2 bd-highlight"><h5><em><u>{{ user.username }}</u></em></h5></div>
			<div class="p-2 bd-highlight">
				<a style="color: #212529" title="Выход из системы" href={% url 'logout' %}>
					<i class="fas fa-sign-out-alt fa-2x"></i></a>
			</div>
		</div>
	</div>
</div>

<div class="container-fluid">
	{% block content %}

		<div class="row d-flex m-3 ">
			<div class="col-12 border">
				<p class="my-3 form-header-admin"><i class="fas fa-users"></i>&nbsp;&nbsp;Пользователи</p>
				<table class="table">
					<thead>
					<tr>
						<th scope="col">Логин</th>
						<th scope="col">Имя</th>
						<th scope="col">Фамилия</th>
						<th scope="col">Электронный адрес</th>
						<th scope="col">Группа</th>
						<th scope="col">Подразделение</th>
						<th scope="col">Дата регистрации</th>
						<th scope="col">Последний вход</th>
						<th scope="col"></th>
					</tr>
					</thead>
					<tbody>
					{% for user in all_users %}
						<tr>
							<td>{{ user.username }}</td>
							<td>{{ user.first_name }}</td>
							<td>{{ user.last_name }}</td>
							<td>{{ user.email }}</td>
							<td>
								{% for group in user.groups.all %}
									{{ group }}
								{% endfor %}
							</td>
							<td>
								{{ user.userprofile.subdivision }}
							</td>
							<td>{{ user.date_joined }}</td>
							<td>{{ user.last_login }}</td>
							<td>
								<div class="btn-group" role="group" aria-label="Basic example">
									{#								<a type="button" class="btn btn-secondary" title="Редактировать" href="change/{{ user.id }}" ><i class="far fa-1x fa-user-edit"></i></a>#}
									<a type="button" class="btn btn-secondary" title="Редактировать" href="{% url "change_user" %}?user_id={{ user.id }}"><i class="far fa-1x fa-user-edit"></i></a>
									<a type="button" class="btn btn-secondary" title="Изменить пароль"><i class="far fa-1x fa-key"></i></a>
									<a type="button" class="btn btn-secondary" title="Удалить" href="delete/{{ user.id }}"><i class="far fa-1x fa-trash-alt"></i></a>
								</div>
							</td>
						</tr>
					{% endfor %}

					</tbody>
				</table>
			</div>
		</div>
	{% endblock content %}
</div>


<!-- Jquery core JavaScript -->
<script src={% static "vendor/jquery/jquery.min.js" %}></script>
<!-- Jquery core Popper -->
<script src={% static "vendor/bootstrap/js/popper.min.js" %}></script>
<!-- Bootstrap core JavaScript -->
{#<script src={% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}></script>#}
<script src={% static "vendor/bootstrap/js/bootstrap.min.js" %}></script>
<!-- Font Awesome core JavaScript -->
<script src={% static "vendor/icons/js/all.min.js" %}></script>
<script src={% static "vendor/message/notify.min.js" %}></script>
<script src={% static "js/my_script_message.js" %}></script>
</body>
</html>

adminIncident/templates/changeuser.html
{% extends "adminincident.html" %}
{% block breadcrumbs %}
	<li><a href={% url 'adminincident' %}>Пользователи</a></li>
	<li><a class="current" href="#">Изменить пользователя</a></li>
{% endblock breadcrumbs %}
{% block content %}

	<div class="row d-flex m-3 ">
		<div class="col-12 border">
			<p class="my-3 form-header-admin"><i class="fas fa-users-cog"></i>&nbsp;&nbsp;Изменить пользователя
				<q class="text-user">{{ user.username }}</q></p>
			<form method="POST" action="{% url "change_user" %}" id="id_form_user" style="min-width: 100%">{% csrf_token %}
				<div style="margin-bottom: 90px">
					<div class="col-12 border border-secondary">
						<input hidden name="user_id" value="{{ user.id }}">
						<div class="form-row">
							<div class="form-group col-md-6">
								<label for="id_first_name">Имя</label>
								<input value="{{ user.first_name }}" type="text" class="form-control" id="id_first_name" name="first_name">
								<small id="id_first_name" class="form-text text-muted">Ввод имени пользователя</small>
							</div>
							<div class="form-group col-md-6">
								<label for="id_last_name">Фамилия</label>
								<input value="{{ user.last_name }}" type="text" class="form-control" id="id_last_name" name="last_name">
								<small id="id_last_name" class="form-text text-muted">Ввод фамилии пользователя</small>
							</div>
						</div>
						<div class="form-row">
							<div class="form-group col-md-6">
								<label for="id_email">Электронный адрес</label>
								<input value="{{ user.email }}" type="email" class="form-control" id="id_email" name="email">
								<small id="id_email" class="form-text text-muted">Ввод электронного адреса РОСГВАРДИИ
								</small>
							</div>
							<div class="form-group col-md-6">
								<label for="id_group">Выберите группу пользователю</label>
								<select id="id_group" class="form-control" multiple name="group">
									{% for group in groups %}
										{% if group in user.groups.all %}
											<option value="{{ group.id }}" selected>{{ group.name }}</option>
										{% else %}
											<option value="{{ group.id }}">{{ group.name }}</option>
										{% endif %}
									{% endfor %}
								</select>
							</div>
							<div class="form-group col-md-6">
								<label for="id_subdivision">Выберите подразделение пользователю</label>
								<select id="id_subdivision" class="form-control" name="subdivision">
									{% for subdivision in subdivisions %}
										{% if subdivision.id == user.userprofile.subdivision_id %}
											<option value="{{ subdivision.id }}" selected>{{ subdivision.name }}</option>
										{% else %}
											<option value="{{ subdivision.id }}">{{ subdivision.name }}</option>
										{% endif %}
									{% endfor %}
								</select>
							</div>
						</div>
					</div>

				</div>

			</form>
			<div class="d-flex justify-content-center panel_buttom">
				<div class="btn-group" role="group" aria-label="Basic example">
					<button type="submit" class="btn btn-outline-dark" form="id_form_user">СОХРАНИТЬ РЕЗУЛЬТАТ
					</button>
				</div>
			</div>
		</div>
	</div>
{% endblock content %}