incidentProject/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, re_path, include

from authOrion.views import StartView, RegisterFormView, LoginFormView, LogoutView, PasswordChangeView
from adminIncident.views import AdminIncidentView

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^adminincident/', include('adminIncident.urls')),
    re_path(r'^orion/', include('orion.urls')),
    re_path(r'^$', login_required(StartView.as_view()), name="start"),

    #Auth
    re_path(r'^register/', RegisterFormView.as_view(), name="register"),
    re_path(r'^login/', LoginFormView.as_view(), name="login"),
    re_path(r'^logout/', LogoutView.as_view(), name="logout"),
    re_path(r'^passwordchange/', PasswordChangeView.as_view(), name="passwordChange"),
]

orion/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import re_path, path, include

from orion.views import headorion_view, event_view, operationalenv_view, face_view, journal_view, analytics_view, about_view, titul_view, org_view, ajax_view

urlpatterns = [

    re_path(r'^headorion$', login_required(headorion_view.HeadOrionView.as_view()), name="headorion"),
    re_path(r'^event/', include([
        re_path(r'^$', event_view.EventView.as_view(), name="event"),
        re_path(r'^change$', event_view.ChangeEventView.as_view(), name="change_event"),
        re_path(r'^delete$', event_view.DeleteEventView.as_view(), name="delete_event"),
    ])),
    re_path(r'^face/', include([
        re_path(r'^$', face_view.FaceView.as_view(), name="face"),
        re_path(r'^add$', face_view.AddFaceView.as_view(), name="add_face"),
        re_path(r'^change$', face_view.ChangeFaceView.as_view(), name="change_face"),
        re_path(r'^delete$', face_view.DeleteFaceView.as_view(), name="delete_face"),
    ])),
    re_path(r'^titul/', include([
        re_path(r'^$', titul_view.TitulView.as_view(), name="titul"),
        re_path(r'^add$', titul_view.AddTitulView.as_view(), name="add_titul"),
        re_path(r'^change$', titul_view.ChangeTitulView.as_view(), name="change_titul"),
        re_path(r'^delete$', titul_view.DeleteTitulView.as_view(), name="delete_titul"),
    ])),
    re_path(r'^org/', include([
        re_path(r'^$', org_view.OrgView.as_view(), name="org"),
        re_path(r'^add$', org_view.AddOrgView.as_view(), name="add_org"),
        re_path(r'^change$', org_view.ChangeOrgView.as_view(), name="change_org"),
        re_path(r'^delete$', org_view.DeleteOrgView.as_view(), name="delete_org"),
    ])),
    re_path(r'^operationalenv/', include([
        re_path(r'^$', operationalenv_view.OperationalEnvView.as_view(), name="operationalenv"),
        re_path(r'^add$', operationalenv_view.AddOperationalEnvView.as_view(), name="add_operationalenv"),
        re_path(r'^change$', operationalenv_view.ChangeOperationalEnvView.as_view(), name="change_operationalenv"),
        re_path(r'^delete$', operationalenv_view.DeleteOperationalEnvView.as_view(), name="delete_operationalenv"),
    ])),
    re_path(r'^journal$', login_required(journal_view.JournalView.as_view()), name="journal"),
    re_path(r'^anlytics$', login_required(analytics_view.AnalyticsView.as_view()), name="analytics"),
    re_path(r'^about$', login_required(about_view.AboutView.as_view()), name="about"),

    # AJAX
    re_path(r'^count_event/', login_required(ajax_view.CountEventView.as_view()), name="count_event"),
    re_path(r'^show_event/', login_required(ajax_view.ShowEventView.as_view()), name="show_event"),

]

orion/models.py
import datetime

from django.contrib.auth.models import User
from django.db import models

from django.db.models.signals import post_save
from django.dispatch import receiver


class Event(models.Model):
    type_message = models.ForeignKey("TypeMessage", on_delete=models.PROTECT, verbose_name="Тип сообщения")
    titul = models.ForeignKey("Titul", blank=True, null=True, on_delete=models.PROTECT, verbose_name="Титул")
    org = models.ManyToManyField("Org", blank=True, verbose_name="Организация")
    date_registratsii = models.DateField(verbose_name="Дата регистрации")
    reg_number = models.CharField(max_length=50, verbose_name="Регистрационный номер")
    region = models.ForeignKey("AdresAte", on_delete=models.PROTECT, verbose_name="Субъект РФ")
    sut_info = models.TextField(verbose_name="Суть информации")
    klassif_priznak_UK = models.ForeignKey("KlassifPriznakUK", blank=True, null=True, on_delete=models.PROTECT, verbose_name="Классифицирующий признак (по статье УК РФ)")
    klassif_priznak_ugroza = models.ForeignKey("KlassifPriznakUgroza", blank=True, null=True, on_delete=models.PROTECT, verbose_name="Классифицирующий признак (угроза)")
    klassif_priznak_text = models.TextField(verbose_name="Классифицирующий признак (текст)", blank=True)
    rezolyutsiya_rukovodstva = models.TextField(verbose_name="Резолюция руководства ВНГ, ГУСБ", blank=True)
    date_start = models.DateField(verbose_name="Дата начало", null=True)
    date_finish = models.DateField(verbose_name="Дата окончания", null=True)
    ispolnitel_organ = models.CharField(max_length=100, blank=True, verbose_name="Исполнитель (Орган)")
    ispolnitel_sotrudnik = models.CharField(max_length=100, blank=True, verbose_name="Исполннитель (сотрудник)")
    info_otrabotki_materiala = models.TextField(verbose_name="Информация, полученная в ходе отработки материала", blank=True)
    identified_face = models.ManyToManyField("Face", blank=True, verbose_name="В ходе проверки выявлены (установленны лица)")
    type_proverki = models.ForeignKey("TypeProverki", blank=True, null=True, on_delete=models.PROTECT, verbose_name="Вид проверки")
    rezult_proverki = models.ForeignKey("ResultProverki", blank=True, null=True, on_delete=models.PROTECT, verbose_name="Результат проверки")
    prinyatie_meri = models.TextField(verbose_name="Принятые меры", blank=True)
    otvet_zayavitelyu = models.TextField(verbose_name="Ответ заявителю", blank=True)
    ispolnenie_rezolyucii = models.TextField(verbose_name="Исполнение резолюции руководства ВНГ, ГУСБ", blank=True)
    date_otveta = models.DateField(verbose_name="Дата ответа заявителю", blank=True, null=True)
    ishodyaschii_nomer = models.CharField(max_length=50, blank=True, verbose_name="Исходящий номер документа")
    operativnaya_obstanovka = models.ForeignKey("OperativnayaObstanovka", blank=True, null=True, on_delete=models.PROTECT, verbose_name="Оперативная обстановка")

    # Свои поля
    date_change = models.DateField(auto_now=True, verbose_name="Дата изменения")
    date_creation = models.DateField(auto_now_add=True, verbose_name="Дата создания")
    user = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name="Пользователь")
    status = models.ForeignKey("Status", on_delete=models.PROTECT, verbose_name="Статус", default="Информационный")
    date_vklyuch_doklad = models.DateField(verbose_name="Дата включения в доклад", blank=True, null=True)
    subdivision = models.ForeignKey("Subdivision", on_delete=models.PROTECT, verbose_name="Подразделение", default="ГУСБ")

    # Доступные запросы
    @staticmethod
    def available_requests(subdivision_pk):
        return Event.objects.all() if subdivision_pk == 1 else Event.objects.filter(subdivision__pk=subdivision_pk)

    # ДоступныЙ запрос
    @staticmethod
    def available_request(subdivision_pk, id):
        return Event.objects.get(id=id) if subdivision_pk == 1 else Event.objects.get(subdivision__pk=subdivision_pk, id=id)


class TypeMessage(models.Model):
    name = models.TextField(verbose_name="Наименование")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Тип сообщения"
        verbose_name_plural = "Типы сообщений"


class Titul(models.Model):
    name = models.CharField(max_length=300, verbose_name="Наименование")
    nomer_vhodyaschego = models.CharField(max_length=300, blank=True, verbose_name="Номер входящего документа")
    date_vhodyaschego = models.DateField(verbose_name="Дата входящего документа", blank=True, null=True)
    otkuda = models.CharField(max_length=100, blank=True, verbose_name="Откуда поступил документ")
    ishodyaschii_nomer = models.CharField(max_length=50, blank=True, verbose_name="Исходящий номер документа")
    date_ishodyaschego = models.DateField(verbose_name="Дата исходящего документа", blank=True, null=True)
    date_vneseniya = models.DateTimeField(verbose_name="Дата вненсения документа в ИБД", auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Титул"
        verbose_name_plural = "Титулы"


class Org(models.Model):
    name = models.CharField(max_length=300, verbose_name="Наименование организации")
    inn_ogrn = models.CharField(max_length=100, blank=True, verbose_name="ИНН (ОГРН)")
    adres_organiz_ate = models.ForeignKey("AdresAte", null=True, blank=True, on_delete=models.PROTECT, verbose_name="Адрес организации (АТЕ)")
    adres_organiz = models.CharField(max_length=100, blank=True, verbose_name="Адрес организации")
    inaya_informaciya = models.TextField(blank=True, verbose_name="Иная информация")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Организация"
        verbose_name_plural = "Организации"


class AdresAte(models.Model):
    name = models.TextField(verbose_name="Наименование")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Адрес АТЕ"
        verbose_name_plural = "Адреса АТЕ"


class KlassifPriznakUK(models.Model):
    name = models.TextField(verbose_name="Наименование")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Классифицирующий признак (по статье УК РФ)"
        verbose_name_plural = "Классифицирующие признаки (по статье УК РФ)"


class KlassifPriznakUgroza(models.Model):
    name = models.TextField(verbose_name="Наименование")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Классифицирующий признак (угроза)"
        verbose_name_plural = "Классифицирующие признаки (угроза)"


class Face(models.Model):
    familiya = models.CharField(max_length=100, verbose_name="Фамилия")
    imya = models.CharField(max_length=100, verbose_name="Имя")
    otchestvo = models.CharField(max_length=100, verbose_name="Отчество")
    date_rojdeniya = models.DateField(verbose_name="Дата рождения")
    mesto_rojdeniya_ATE = models.ForeignKey("AdresAte", on_delete=models.PROTECT, blank=True, null=True, verbose_name="Место рождения (АТЕ))")
    mesto_rojdeniya_raion = models.CharField(max_length=100, blank=True, verbose_name="Место рождения (район)")
    mesto_rojdeniya_np = models.CharField(max_length=100, blank=True, verbose_name="Место рождения (н.п.)")
    zvanie = models.ForeignKey("Zvanie", on_delete=models.PROTECT, verbose_name="Воинское (специальное) звание")
    dopolnitelnaya_info = models.TextField(verbose_name="Дополнительная информация", blank=True)
    rodstvennie_svyazi = models.ManyToManyField('self', blank=True, symmetrical=False, verbose_name="Родственные связи")

    def __str__(self):
        return "{} {} {} , {}".format(self.familiya, self.imya, self.otchestvo, datetime.datetime.strftime(self.date_rojdeniya, '%d.%m.%Y'))

    class Meta:
        unique_together = (['familiya', 'imya', 'otchestvo', 'date_rojdeniya'])
        verbose_name = "Лицо"
        verbose_name_plural = "Лица"


class Zvanie(models.Model):
    name = models.TextField(verbose_name="Наименование")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Звание"
        verbose_name_plural = "Звания"


class TypeProverki(models.Model):
    name = models.TextField(verbose_name="Наименование")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Вид проверки"
        verbose_name_plural = "Виды проверок"


class ResultProverki(models.Model):
    name = models.TextField(verbose_name="Наименование")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Результа проверки"
        verbose_name_plural = "Результаты проверок"


class OperativnayaObstanovka(models.Model):
    date = models.DateField(verbose_name="Дата")
    klassif_priznak_ugroza = models.ForeignKey("KlassifPriznakUgroza", null=True, blank=True, on_delete=models.PROTECT, verbose_name="Классифицирующий признак (угроза)")
    klassif_priznak_text = models.TextField(verbose_name="Классифицирующий признак (текст)", blank=True)
    sut_info = models.TextField(verbose_name="Суть информации")
    prinyatie_meri = models.TextField(verbose_name="Принятые меры", blank=True)

    def __str__(self):
        return self.sut_info

    class Meta:
        verbose_name = "Оперативная обстановка"
        verbose_name_plural = "Оперативные обстановки"


class Status(models.Model):
    name = models.TextField(verbose_name="Наименование")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Статус"
        verbose_name_plural = "Статусы"


class Subdivision(models.Model):
    name = models.CharField(max_length=150, verbose_name="Наименование")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Подразделение"
        verbose_name_plural = "Подразделения"


# Кастомизируем модель User и добавляем дополнительные поля
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)

orion/views/about_view.py
from django.shortcuts import render
from django.views.generic import TemplateView

from orion.views.abstract.orion_view import OrionView


class AboutView(OrionView):
    group_required = ['Орион']
    def get(self, request, *args, **kwargs):
        return render(request, "about.html")

orion/views/ajax_view.py
from django.http import JsonResponse
from django.shortcuts import render

from orion.forms import EventForm, TitulForm
from orion.models import Event, Titul
from orion.views.abstract.orion_view import OrionView
from django.forms import inlineformset_factory


class CountEventView(OrionView):
    group_required = ['Орион']
    regions = {"ОСБ ЦО": "Центральный федеральный округ",
               "ОСБ СЗО": "Северо-Западный федеральный округ",
               "ОСБ ЮО": "Южный федеральный округ",
               "ОСБ СКО": "Северо-Кавказкий федеральный округ",
               "ОСБ ПривО": "Приволжский федеральный округ",
               "ОСБ УрО": "Уральский федеральный округ",
               "ОСБ СибО": "Сибирский федеральный округ",
               "ОСБ ВО": "Восточный федеральный округ"
               }

    def get(self, request, *args, **kwargs):
        region = request.GET.get("region")
        for key, items in self.regions.items():
            if items == region:
                element = Event.objects.filter(subdivision__name=key).count()
                break
            else:
                element = 0
        context = {"element": element}
        return JsonResponse(context)


class ShowEventView(OrionView):
    group_required = ['Орион']

    def get(self, request, *args, **kwargs):
        event_id = request.GET.get("event_id")
        event = Event.available_request(request.user.userprofile.subdivision.pk, event_id)
        # event_form = EventForm(None, instance=event)
        context = {"event": event}
        return render(request, "event_body_modal.html", context)

orion/views/analytics_view.py
from django.http import JsonResponse
from django.shortcuts import render
from django.views.generic import TemplateView

from orion.models import Event
from orion.views.abstract.orion_view import OrionView


class AnalyticsView(OrionView):
    group_required = ['Орион']

    def get(self, request, *args, **kwargs):
        context = {"all_event": Event.objects.all().count()}
        return render(request, "analytics.html", context)

orion/views/headorion_view.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import TemplateView

from orion.views.abstract.orion_view import OrionView


class HeadOrionView(OrionView):
    group_required = ['Орион']
    def get(self, request, *args, **kwargs):
        return render(request, "headorion.html")

orion/views/journal_view.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import TemplateView

from orion.models import Event
from orion.views.abstract.orion_view import OrionView


class JournalView(OrionView):
    group_required = ['Орион']
    template_name = "journal.html"

    def get(self, request, *args, **kwargs):
        try:
            events = Event.available_requests(request.user.userprofile.subdivision.pk).order_by('-id')
            return render(request, self.template_name, {"events": events})
        except:
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

orion/templates/face.html
{% extends "base.html" %}
{% load static %}
{% block title %}Лицо{% endblock title %}
{% block name_page %}<i class="fas fa-address-card"></i>&nbsp;Лицо{% endblock name_page %}
{% block breadcrumbs %}
    <li><a class="current" href={% url 'face' %}>Лица</a></li>
{% endblock breadcrumbs %}
{% block content %}
    <div class="row d-flex justify-content-center my-4" style="height:700px;overflow-y:auto;">
        <div class="col-12">
            <button class="m-2 btn btn-sm btn-secondary" onclick="add_face()">
                <img alt="#" height="16" src="{% static "vendor/color_icons/db_add_8760.ico" %}"/>&nbsp;Добавить лицо
            </button>
            <table id="id_table_face" class="table table-striped table-bordered compact-table" style="width:100%">
                <thead>
                <tr>
                    <th>Фамилия</th>
                    <th>Имя</th>
                    <th>Отчество</th>
                    <th>Дата рождения</th>
                    <th>Место рождения (АТЕ)</th>
                    <th>Место рождения (район)</th>
                    <th>Место рождения (н.п.)</th>
                    <th>Воинское (специальное) звание</th>
                    <th>Дополнительная информация</th>
                    <th>Связанные инциденты</th>
                    <th>Действие</th>
                </tr>
                </thead>
                <tbody>
                {% for face  in faces %}
                    <tr>
                        <td>{{ face.familiya }}</td>
                        <td>{{ face.imya }}</td>
                        <td>{{ face.otchestvo }}</td>
                        <td>{{ face.date_rojdeniya|date:"d.m.Y" }}</td>
                        <td>{{ face.mesto_rojdeniya_ATE|default_if_none:"" }}</td>
                        <td>{{ face.mesto_rojdeniya_raion }}</td>
                        <td>{{ face.mesto_rojdeniya_np }}</td>
                        <td>{{ face.zvanie }}</td>
                        <td>{{ face.dopolnitelnaya_info }}</td>

                        <td>
                            <ul type="square">
                                {% for event in face.event_set.all %}
                                    <li><a onclick="show_event({{ event.id }})" href="#" class="text-danger">{{ event.reg_number }}</a></li>

                                {% endfor %}
                            </ul>
                        </td>
                        <td>
                            <div class="btn-group" role="group" aria-label="Basic example">
                                <a type="button" class="btn btn-sm btn-secondary" title="Редактировать" href="#" onclick="change_face({{ face.id }})"> <i class="far fa-edit"></i> </a>
                                <a type="button" class="btn btn-sm  btn-secondary" title="Удалить" href="#" onclick="delete_face({{ face.id }},'{{ face }}')"><i class="far fa-1x fa-trash-alt"></i></a>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    <!--Модальное окно события -->
    <div class="modal fade bd-example-modal-xl" tabindex="-1" role="dialog" aria-labelledby="myExtraLargeModalLabel" aria-hidden="true" id="id_modal_event">
        <div class="modal-dialog modal-xl">
            <div class="modal-content" id="id_modal_content">

            </div>
        </div>
    </div>
    <!--Модальное окно лица -->
    <div class="modal fade" id="id_modal_face" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content" id="id_modal_content_face">
            </div>
        </div>
    </div>
    <!--Модальное окно удаления -->
    <div class="modal fade" id="id_modal_del" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5>Вы точно хотите удалить запись?</h5>
                </div>
                <div class="modal-body" id="id_body_del">

                </div>
                <div class="modal-footer" id="id_footer_del">
                </div>
            </div>
        </div>
    </div>

{% endblock content %}
{% block js %}
    <script>
        $(document).ready(function () {
            $('#id_table_face').DataTable(
                {
                    "pageLength": 5,
                    "lengthChange": false,
                    "language": {
                        "url": "{% static "vendor/data_tables/ru.json" %}"
                    }
                }
            );
        });

        function show_event(event_id) {
            var params = {
                "event_id": event_id
            };
            $.get("{% url "show_event" %}", params, function (data) {
                $('#id_modal_event').modal('toggle');
                $('#id_modal_content').empty().append(data);

            })
        }

        function add_face() {
            $.get("{% url "add_face" %}", function (data) {
                $('#id_modal_face').modal('toggle');
                $('#id_modal_content').empty().append(data);
            })
        }

        function change_face(face_id) {
            var params = {
                "face_id": face_id
            };
            $.get("{% url "change_face" %}", params, function (data) {
                $('#id_modal_face').modal('toggle');
                $('#id_modal_content_face').empty().append(data);
            })
        }

        function delete_face(face_id, face_name) {
            $('#id_modal_del').modal('toggle');
            $('#id_body_del').empty().append(face_name);
            $('#id_footer_del').empty().append("<a type=\"button\" class=\"btn btn-sm  btn-secondary\" title=\"Удалить\" href=\"{% url "delete_face" %}?face_id=" + face_id + "\"><i class=\"far fa-1x fa-trash-alt\"></i> ДА</a>");
        }
    </script>
{% endblock js %}

orion/templates/face_content_modal_add.html
<div class="modal-header">
    <h4>Добавить лицо</h4>
</div>
<div class="modal-body">
    <form class="compact-form" method="post" action="{% url "add_face" %}" id="id_form_face">
        {% csrf_token %}
        {% for field in face_form %}
            <div class="form-group">
                {{ field.label_tag }}
                <div>{{ field }}</div>
                <div class="error">{{ field.errors }}</div>
            </div>
        {% endfor %}
    </form>
    <div class="modal-footer">
        <button type="submit" class="btn btn-sm btn-secondary" form="id_form_face"><i class="far fa-save"></i>&nbsp;Сохранить</button>
    </div>
</div>

orion/templates/headorion.html
{% extends "base.html" %}
{% block content %}
            <div class="row d-flex justify-content-center ">
                <marquee behavior="alternate" direction="right">На стадии разработки</marquee>
            </div>
{% endblock content %}

<!-- Menu Toggle Script -->

orion/templates/operationalenv_content_modal_add_.html
<div class="modal-header">
    <h4>Добавить оперативную обстановку</h4>
</div>
<div class="modal-body">
    <form class="compact-form" method="post" action="{% url "add_operationalenv" %}" id="id_form_operationalenv">
        {% csrf_token %}
        {% for field in operationalenv_form %}
            <div class="form-group">
                {{ field.label_tag }}
                <div>{{ field }}</div>
                <div class="error">{{ field.errors }}</div>
            </div>
        {% endfor %}
    </form>
    <div class="modal-footer">
        <button type="submit" class="btn btn-sm btn-secondary" form="id_form_operationalenv"><i class="far fa-save"></i>&nbsp;Сохранить</button>
    </div>
</div>

orion/templates/operationalenv_content_modal_change.html
<div class="modal-header">
    <h4>Изменить оперативную обстановку</h4>
</div>
<div class="modal-body">
    <form class="compact-form" method="post" action="{% url "change_operationalenv" %}" id="id_form_operationalenv">
        {% csrf_token %}
        <input hidden name="operationalenv_id" value="{{ operationalenv_id }}">
        {% for field in operationalenv_form %}
            <div class="form-group">
                {{ field.label_tag }}
                <div>{{ field }}</div>
                <div class="error">{{ field.errors }}</div>
            </div>
        {% endfor %}
    </form>
    <div class="modal-footer">
        <button type="submit" class="btn btn-sm btn-secondary" form="id_form_operationalenv"><i class="far fa-save"></i>&nbsp;Сохранить</button>
    </div>
</div>

orion/templates/org_content_modal_add.html
<div class="modal-header">
    <h4>Добавить организацию</h4>
</div>
<div class="modal-body">
    <form class="compact-form" method="post" action="{% url "add_org" %}" id="id_form_org">
        {% csrf_token %}
        {% for field in org_form %}
            <div class="form-group">
                {{ field.label_tag }}
                <div>{{ field }}</div>
                <div class="error">{{ field.errors }}</div>
            </div>
        {% endfor %}
    </form>
    <div class="modal-footer">
        <button type="submit" class="btn btn-sm btn-secondary" form="id_form_org"><i class="far fa-save"></i>&nbsp;Сохранить</button>
    </div>
</div>

orion/templates/org_content_modal_change.html
<div class="modal-header">
    <h4>Изменить организацию</h4>
</div>
<div class="modal-body">
    <form class="compact-form" method="post" action="{% url "change_org" %}" id="id_form_org">
        {% csrf_token %}
        <input hidden name="org_id" value="{{ org_id }}">
        {% for field in org_form %}
            <div class="form-group">
                {{ field.label_tag }}
                <div>{{ field }}</div>
                <div class="error">{{ field.errors }}</div>
            </div>
        {% endfor %}
    </form>
    <div class="modal-footer">
        <button type="submit" class="btn btn-sm btn-secondary" form="id_form_org"><i class="far fa-save"></i>&nbsp;Сохранить</button>
    </div>
</div>

orion/templates/titul_content_modal_change.html
<div class="modal-header">
    <h4>Изменить титул документа</h4>
</div>
<div class="modal-body">
    <form class="compact-form" method="post" id="id_form_titul" action="{% url "change_titul" %}">
        {% csrf_token %}
        <input hidden name="titul_id" value="{{ titul_id }}">
        {% for field in titul_form %}
            <div class="form-group">
                {{ field.label_tag }}
                <div>{{ field }}</div>
                <div class="error">{{ field.errors }}</div>
            </div>
        {% endfor %}
    </form>
    <div class="modal-footer">
        <button type="submit" class="btn btn-sm btn-secondary" form="id_form_titul"><i class="far fa-save"></i>&nbsp;Сохранить</button>
    </div>
</div>